modules:
  likelihood_mod:
    class: 'src.Bayesian_state.problems.modules.likelihood.LikelihoodModule'
    kwargs: {beta: 15.}
  memory_mod:
    class: 'src.Bayesian_state.problems.modules.memory.DualMemoryModule'
    kwargs: {
      w0: 0.8, 
      gamma: 0.8,
    }

agenda:
  - likelihood_mod
  - memory_mod