modules:
  likelihood_mod:
    class: 'src.Bayesian_state.problems.modules.likelihood.LikelihoodModule'
    kwargs: {}
  perception_mod:
    class: 'src.Bayesian_state.problems.modules.perception.PerceptionModule'

agenda:
  - perception_mod
  - likelihood_mod
  - __self__