modules:
  likelihood_mod:
    class: 'src.Bayesian_state.problems.modules.likelihood.LikelihoodModule'
    kwargs: {
      beta: 5.
    }
  memory_mod:
    class: 'src.Bayesian_state.problems.modules.memory.DualMemoryModule'
    kwargs: {
      w0: 0.9, 
      gamma: 0.7,
    }
  perception_mod:
    class: 'src.Bayesian_state.problems.modules.perception.PerceptionModule'

agenda:
  - perception_mod
  - likelihood_mod
  - memory_mod