modules:
  perception_mod:
    class: 'src.Bayesian_state.problems.modules.perception.PerceptionModule'
  hypo_transitions_mod:
    class: 'src.Bayesian_state.problems.modules.hypo_transitions.DynamicHypothesisModule'
    kwargs: {
      "strategies": original_strategies_a,
      "init_num":8,
    } 
  likelihood_mod:
    class: 'src.Bayesian_state.problems.modules.likelihood.LikelihoodModule'
    kwargs: {
      beta: 10.
    }
  memory_mod:
    class: 'src.Bayesian_state.problems.modules.memory.DualMemoryModule'
    kwargs: {
      w0: 0.05, 
      gamma: 0.9,
    }

agenda:
  - perception_mod
  - hypo_transitions_mod
  - likelihood_mod
  - memory_mod