modules:
  perception_mod:
    class: 'src.Bayesian_state.problems.modules.perception.PerceptionModule'
  hypo_transitions_mod:
    class: 'src.Bayesian_state.problems.modules.hypo_transitions.FixedNumHypothesisModule'
    kwargs: {
      fixed_hypo_num: 30,
      init_strategy: 'random',
      transition_mode: 'top_posterior',
      throw_num: 5,
    }
  likelihood_mod:
    class: 'src.Bayesian_state.problems.modules.likelihood.LikelihoodModule'
    kwargs: {
      beta: 5.
    }
  memory_mod:
    class: 'src.Bayesian_state.problems.modules.memory.DualMemoryModule'
    kwargs: {
      w0: 0.3, 
      gamma: 0.9,
    }

agenda:
  - perception_mod
  - hypo_transitions_mod
  - likelihood_mod
  - memory_mod